replicaCount: 1

image:
  repository: palash9422/form-frontend       # your Docker Hub repo for frontend image
  tag: v1                                  # the tag you pushed
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80


resources: {}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: true
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
          service:
            port: 80

