replicaCount: 1

image:
  repository: palash9422/form-frontend       # your Docker Hub repo for frontend image
  tag: v1                                  # the tag you pushed
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

