replicaCount: 1

image:
  repository: palash9422/form-frontend       # your Docker Hub repo for frontend image
  tag: v1                                  # the tag you pushed
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

