replicaCount: 1

image:
  repository: palash9422/form-backend
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

containerPort: 3000

env:
  - name: MONGODB_URL
    value: mongodb://mongodb.mongodb.svc.cluster.local:27017/formdb

resources: {}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
