serviceAccount:
  create: true
  name: ""

replicaCount: 1

image:
  repository: mongo
  tag: "4.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

resources: {}

persistence:
  enabled: false

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: mongodb.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


autoscaling:
  enabled: false
