replicaCount: 1

image:
  repository: mongo
  tag: "4.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

resources: {}

persistence:
  enabled: false
  # If you want persistent storage, configure PVC here
  # size: 1Gi
  # storageClass: ""

